/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { BodyAddDeviceDevicesAddPostDeviceUuid } from './bodyAddDeviceDevicesAddPostDeviceUuid';

export interface BodyAddDeviceDevicesAddPost {
  device_name: string;
  device_uuid?: BodyAddDeviceDevicesAddPostDeviceUuid;
}
