/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { BodyCreateTraceV1ApiTracesPostConfigurationId } from './bodyCreateTraceV1ApiTracesPostConfigurationId';
import type { BodyCreateTraceV1ApiTracesPostDeviceId } from './bodyCreateTraceV1ApiTracesPostDeviceId';

export interface BodyCreateTraceV1ApiTracesPost {
  trace_name: string;
  trace_file: Blob;
  trace_timestamp: string;
  configuration_id?: BodyCreateTraceV1ApiTracesPostConfigurationId;
  device_id?: BodyCreateTraceV1ApiTracesPostDeviceId;
}
