/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigCreateTracingTool } from './configCreateTracingTool';
import type { ConfigCreateDefaultDuration } from './configCreateDefaultDuration';

export interface ConfigCreate {
  config_name: string;
  config_text: string;
  tracing_tool?: ConfigCreateTracingTool;
  default_duration?: ConfigCreateDefaultDuration;
}
