/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigUpdateTracingTool } from './configUpdateTracingTool';
import type { ConfigUpdateDefaultDuration } from './configUpdateDefaultDuration';

export interface ConfigUpdate {
  config_name: string;
  config_text: string;
  tracing_tool?: ConfigUpdateTracingTool;
  default_duration?: ConfigUpdateDefaultDuration;
}
