/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigResponseTracingTool } from './configResponseTracingTool';
import type { ConfigResponseDefaultDuration } from './configResponseDefaultDuration';

export interface ConfigResponse {
  config_id: string;
  config_name: string;
  config_text: string;
  tracing_tool?: ConfigResponseTracingTool;
  default_duration?: ConfigResponseDefaultDuration;
}
