/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceUpdateRequestDeviceName } from './deviceUpdateRequestDeviceName';
import type { DeviceUpdateRequestDeviceUuid } from './deviceUpdateRequestDeviceUuid';
import type { DeviceUpdateRequestLastSeen } from './deviceUpdateRequestLastSeen';
import type { DeviceUpdateRequestLastStatus } from './deviceUpdateRequestLastStatus';
import type { DeviceUpdateRequestHost } from './deviceUpdateRequestHost';

export interface DeviceUpdateRequest {
  device_name?: DeviceUpdateRequestDeviceName;
  device_uuid?: DeviceUpdateRequestDeviceUuid;
  last_seen?: DeviceUpdateRequestLastSeen;
  last_status?: DeviceUpdateRequestLastStatus;
  host?: DeviceUpdateRequestHost;
}
