/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceCreateRequestDeviceUuid } from './deviceCreateRequestDeviceUuid';
import type { DeviceCreateRequestLastSeen } from './deviceCreateRequestLastSeen';
import type { DeviceCreateRequestLastStatus } from './deviceCreateRequestLastStatus';
import type { DeviceCreateRequestHost } from './deviceCreateRequestHost';

export interface DeviceCreateRequest {
  device_id: string;
  device_name: string;
  device_uuid?: DeviceCreateRequestDeviceUuid;
  last_seen?: DeviceCreateRequestLastSeen;
  last_status?: DeviceCreateRequestLastStatus;
  host?: DeviceCreateRequestHost;
}
