/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { ExportResultV1ApiGroupResultsQueryIdExportGetFileFormat } from './exportResultV1ApiGroupResultsQueryIdExportGetFileFormat';

export type ExportResultV1ApiGroupResultsQueryIdExportGetParams = {
/**
 * Comma-separated Trace IDs
 */
trace_ids: string;
/**
 * Export format
 */
file_format: ExportResultV1ApiGroupResultsQueryIdExportGetFileFormat;
};
