/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat } from './exportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat';

export type ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetParams = {
/**
 * Export format
 */
file_format: ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat;
};
