/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */

export type ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat = typeof ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat[keyof typeof ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportResultV1ApiGroupResultsTraceIdsQueryIdExportGetFileFormat = {
  csv: 'csv',
  tsv: 'tsv',
  json: 'json',
} as const;
