/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */

export type GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetParams = {
/**
 * Number of traces to return
 */
n?: number | null;
/**
 * Comma-separated device IDs
 */
devices?: string | null;
};
