/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */

export type GetTracesV1ApiTracesGetParams = {
/**
 * Field to sort by
 */
sort_by?: string | null;
/**
 * Filter by device ID
 */
device_id?: string | null;
/**
 * Limit number of results
 */
limit?: number | null;
};
