/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { HostWithStatusHostKey } from './hostWithStatusHostKey';
import type { HostWithStatusLastSeen } from './hostWithStatusLastSeen';

export interface HostWithStatus {
  host_name?: string;
  host_type?: string;
  host_key?: HostWithStatusHostKey;
  last_seen?: HostWithStatusLastSeen;
  status: string;
}
