/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { JobProgressUpdateMessage } from './jobProgressUpdateMessage';
import type { JobProgressUpdateTraceId } from './jobProgressUpdateTraceId';

export interface JobProgressUpdate {
  device_id: string;
  status: string;
  message?: JobProgressUpdateMessage;
  trace_id?: JobProgressUpdateTraceId;
}
