/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { JobRequestResponseDuration } from './jobRequestResponseDuration';
import type { JobRequestResponseResultSummary } from './jobRequestResponseResultSummary';

export interface JobRequestResponse {
  job_id: string;
  config_id: string;
  device_serials: string[];
  status: string;
  created_at: string;
  updated_at: string;
  duration?: JobRequestResponseDuration;
  result_summary?: JobRequestResponseResultSummary;
}
