/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */

export interface PendingJob {
  job_device_id: string;
  job_id: string;
  config_id: string;
  device_id: string;
  device_uuid: string;
  duration: number;
  status: string;
}
