/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { SrcApiTracesTraceWithDeviceTraceHtmlFilename } from './srcApiTracesTraceWithDeviceTraceHtmlFilename';
import type { SrcApiTracesTraceWithDeviceHostName } from './srcApiTracesTraceWithDeviceHostName';
import type { SrcApiTracesTraceWithDeviceConfigurationId } from './srcApiTracesTraceWithDeviceConfigurationId';

export interface SrcApiTracesTraceWithDevice {
  trace_id: string;
  trace_name: string;
  trace_timestamp: string;
  trace_filename: string;
  device_id: string;
  device_name: string;
  trace_html_filename?: SrcApiTracesTraceWithDeviceTraceHtmlFilename;
  host_name?: SrcApiTracesTraceWithDeviceHostName;
  configuration_id?: SrcApiTracesTraceWithDeviceConfigurationId;
}
