/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { TraceUpdateDeviceId } from './traceUpdateDeviceId';

export interface TraceUpdate {
  trace_name: string;
  device_id?: TraceUpdateDeviceId;
}
