/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { TraceDetailHostName } from './traceDetailHostName';
import type { TraceDetailTraceHtmlFilename } from './traceDetailTraceHtmlFilename';
import type { TraceDetailConfigurationId } from './traceDetailConfigurationId';
import type { TraceDetailConfigurationName } from './traceDetailConfigurationName';
import type { TraceDetailConfigurationType } from './traceDetailConfigurationType';

export interface TraceDetail {
  trace_id: string;
  trace_name: string;
  trace_timestamp: string;
  trace_filename: string;
  device_id: string;
  device_name: string;
  host_name?: TraceDetailHostName;
  trace_html_filename?: TraceDetailTraceHtmlFilename;
  configuration_id?: TraceDetailConfigurationId;
  configuration_name?: TraceDetailConfigurationName;
  configuration_type?: TraceDetailConfigurationType;
}
