/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */

export interface TraceCreateResponse {
  trace_id: string;
  trace_name: string;
  trace_timestamp: string;
  trace_filename: string;
}
