/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import type { TraceCreateRequestDeviceId } from './traceCreateRequestDeviceId';
import type { TraceCreateRequestHostName } from './traceCreateRequestHostName';
import type { TraceCreateRequestConfigurationId } from './traceCreateRequestConfigurationId';
import type { TraceCreateRequestTraceHtmlFilename } from './traceCreateRequestTraceHtmlFilename';

export interface TraceCreateRequest {
  trace_id: string;
  trace_name: string;
  device_id?: TraceCreateRequestDeviceId;
  trace_timestamp: string;
  trace_filename: string;
  host_name?: TraceCreateRequestHostName;
  configuration_id?: TraceCreateRequestConfigurationId;
  trace_html_filename?: TraceCreateRequestTraceHtmlFilename;
}
