/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Prism Platform API
 * API for managing traces, configurations, devices, and queries
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AddHostRequest,
  BodyCreateTraceV1ApiTracesPost,
  Config,
  ConfigCreate,
  ConfigResponse,
  ConfigUpdate,
  Device,
  DeviceCreate,
  DeviceCreateRequest,
  DeviceResponse,
  DeviceUpdate,
  DeviceUpdateRequest,
  ExportResultV1ApiGroupResultsQueryIdExportGetParams,
  ExportResultV1ApiResultsTraceIdQueryIdExportGetParams,
  GenerateHostKeyResponse,
  GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetParams,
  GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetParams,
  GetJsonResultV1ApiGroupResultsQueryIdJsonGetParams,
  GetTracesV1ApiTracesGetParams,
  HTTPValidationError,
  HostWithStatus,
  JobDeviceStatusUpdate,
  JobProgressUpdate,
  JobRequestCreate,
  JobRequestResponse,
  JobStatusUpdate,
  PendingJob,
  Query,
  QueryCreate,
  QueryUpdate,
  SrcApiConfigurationsTraceWithDevice,
  SrcApiTracesTraceWithDevice,
  TraceCreateRequest,
  TraceCreateResponse,
  TraceDetail,
  TraceUpdate,
  UploadFileV1ApiWorkerStorageUploadPostParams
} from './schemas';

import axiosInstance from './axios';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * Get all hosts
 * @summary Get Hosts
 */
export const getHostsV1ApiHostsGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<HostWithStatus[]>(
    {url: `/v1/api/hosts`, method: 'GET'
    },
    options);
  }



export const getGetHostsV1ApiHostsGetKey = () => [`/v1/api/hosts`] as const;

export type GetHostsV1ApiHostsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getHostsV1ApiHostsGet>>>
export type GetHostsV1ApiHostsGetQueryError = unknown

/**
 * @summary Get Hosts
 */
export const useGetHostsV1ApiHostsGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getHostsV1ApiHostsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetHostsV1ApiHostsGetKey() : null);
  const swrFn = () => getHostsV1ApiHostsGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Add a new host
 * @summary Add Host
 */
export const addHostV1ApiHostsPost = (
    addHostRequest: AddHostRequest,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/hosts/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addHostRequest
    },
    options);
  }



export const getAddHostV1ApiHostsPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: AddHostRequest }) => {
    return addHostV1ApiHostsPost(arg, options);
  }
}
export const getAddHostV1ApiHostsPostMutationKey = () => [`/v1/api/hosts/`] as const;

export type AddHostV1ApiHostsPostMutationResult = NonNullable<Awaited<ReturnType<typeof addHostV1ApiHostsPost>>>
export type AddHostV1ApiHostsPostMutationError = HTTPValidationError

/**
 * @summary Add Host
 */
export const useAddHostV1ApiHostsPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addHostV1ApiHostsPost>>, TError, Key, AddHostRequest, Awaited<ReturnType<typeof addHostV1ApiHostsPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddHostV1ApiHostsPostMutationKey();
  const swrFn = getAddHostV1ApiHostsPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Generate and set a new key for the host
 * @summary Generate Key
 */
export const generateKeyV1ApiHostsHostIdKeyPost = (
    hostId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<GenerateHostKeyResponse>(
    {url: `/v1/api/hosts/${hostId}/key`, method: 'POST'
    },
    options);
  }



export const getGenerateKeyV1ApiHostsHostIdKeyPostMutationFetcher = (hostId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return generateKeyV1ApiHostsHostIdKeyPost(hostId, options);
  }
}
export const getGenerateKeyV1ApiHostsHostIdKeyPostMutationKey = (hostId: string,) => [`/v1/api/hosts/${hostId}/key`] as const;

export type GenerateKeyV1ApiHostsHostIdKeyPostMutationResult = NonNullable<Awaited<ReturnType<typeof generateKeyV1ApiHostsHostIdKeyPost>>>
export type GenerateKeyV1ApiHostsHostIdKeyPostMutationError = HTTPValidationError

/**
 * @summary Generate Key
 */
export const useGenerateKeyV1ApiHostsHostIdKeyPost = <TError = HTTPValidationError>(
  hostId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof generateKeyV1ApiHostsHostIdKeyPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof generateKeyV1ApiHostsHostIdKeyPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getGenerateKeyV1ApiHostsHostIdKeyPostMutationKey(hostId);
  const swrFn = getGenerateKeyV1ApiHostsHostIdKeyPostMutationFetcher(hostId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Delete a host by ID
 * @summary Delete Host
 */
export const deleteHostV1ApiHostsHostIdDeletePost = (
    hostId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/hosts/${hostId}/delete`, method: 'POST'
    },
    options);
  }



export const getDeleteHostV1ApiHostsHostIdDeletePostMutationFetcher = (hostId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteHostV1ApiHostsHostIdDeletePost(hostId, options);
  }
}
export const getDeleteHostV1ApiHostsHostIdDeletePostMutationKey = (hostId: string,) => [`/v1/api/hosts/${hostId}/delete`] as const;

export type DeleteHostV1ApiHostsHostIdDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteHostV1ApiHostsHostIdDeletePost>>>
export type DeleteHostV1ApiHostsHostIdDeletePostMutationError = HTTPValidationError

/**
 * @summary Delete Host
 */
export const useDeleteHostV1ApiHostsHostIdDeletePost = <TError = HTTPValidationError>(
  hostId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteHostV1ApiHostsHostIdDeletePost>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteHostV1ApiHostsHostIdDeletePost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteHostV1ApiHostsHostIdDeletePostMutationKey(hostId);
  const swrFn = getDeleteHostV1ApiHostsHostIdDeletePostMutationFetcher(hostId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get all devices with status information
 * @summary Get Devices
 */
export const getDevicesV1ApiDevicesGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Device[]>(
    {url: `/v1/api/devices`, method: 'GET'
    },
    options);
  }



export const getGetDevicesV1ApiDevicesGetKey = () => [`/v1/api/devices`] as const;

export type GetDevicesV1ApiDevicesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDevicesV1ApiDevicesGet>>>
export type GetDevicesV1ApiDevicesGetQueryError = unknown

/**
 * @summary Get Devices
 */
export const useGetDevicesV1ApiDevicesGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDevicesV1ApiDevicesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDevicesV1ApiDevicesGetKey() : null);
  const swrFn = () => getDevicesV1ApiDevicesGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a new device
 * @summary Create Device
 */
export const createDeviceV1ApiDevicesPost = (
    deviceCreate: DeviceCreate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Device>(
    {url: `/v1/api/devices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceCreate
    },
    options);
  }



export const getCreateDeviceV1ApiDevicesPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: DeviceCreate }) => {
    return createDeviceV1ApiDevicesPost(arg, options);
  }
}
export const getCreateDeviceV1ApiDevicesPostMutationKey = () => [`/v1/api/devices`] as const;

export type CreateDeviceV1ApiDevicesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDeviceV1ApiDevicesPost>>>
export type CreateDeviceV1ApiDevicesPostMutationError = HTTPValidationError

/**
 * @summary Create Device
 */
export const useCreateDeviceV1ApiDevicesPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createDeviceV1ApiDevicesPost>>, TError, Key, DeviceCreate, Awaited<ReturnType<typeof createDeviceV1ApiDevicesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateDeviceV1ApiDevicesPostMutationKey();
  const swrFn = getCreateDeviceV1ApiDevicesPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Edit an existing device
 * @summary Edit Device
 */
export const editDeviceV1ApiDevicesDeviceIdEditPost = (
    deviceId: string,
    deviceUpdate: DeviceUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Device>(
    {url: `/v1/api/devices/${deviceId}/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceUpdate
    },
    options);
  }



export const getEditDeviceV1ApiDevicesDeviceIdEditPostMutationFetcher = (deviceId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: DeviceUpdate }) => {
    return editDeviceV1ApiDevicesDeviceIdEditPost(deviceId, arg, options);
  }
}
export const getEditDeviceV1ApiDevicesDeviceIdEditPostMutationKey = (deviceId: string,) => [`/v1/api/devices/${deviceId}/edit`] as const;

export type EditDeviceV1ApiDevicesDeviceIdEditPostMutationResult = NonNullable<Awaited<ReturnType<typeof editDeviceV1ApiDevicesDeviceIdEditPost>>>
export type EditDeviceV1ApiDevicesDeviceIdEditPostMutationError = HTTPValidationError

/**
 * @summary Edit Device
 */
export const useEditDeviceV1ApiDevicesDeviceIdEditPost = <TError = HTTPValidationError>(
  deviceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof editDeviceV1ApiDevicesDeviceIdEditPost>>, TError, Key, DeviceUpdate, Awaited<ReturnType<typeof editDeviceV1ApiDevicesDeviceIdEditPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEditDeviceV1ApiDevicesDeviceIdEditPostMutationKey(deviceId);
  const swrFn = getEditDeviceV1ApiDevicesDeviceIdEditPostMutationFetcher(deviceId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Delete a device
 * @summary Delete Device
 */
export const deleteDeviceV1ApiDevicesDeviceIdDeletePost = (
    deviceId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/devices/${deviceId}/delete`, method: 'POST'
    },
    options);
  }



export const getDeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationFetcher = (deviceId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteDeviceV1ApiDevicesDeviceIdDeletePost(deviceId, options);
  }
}
export const getDeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationKey = (deviceId: string,) => [`/v1/api/devices/${deviceId}/delete`] as const;

export type DeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDeviceV1ApiDevicesDeviceIdDeletePost>>>
export type DeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationError = HTTPValidationError

/**
 * @summary Delete Device
 */
export const useDeleteDeviceV1ApiDevicesDeviceIdDeletePost = <TError = HTTPValidationError>(
  deviceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteDeviceV1ApiDevicesDeviceIdDeletePost>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteDeviceV1ApiDevicesDeviceIdDeletePost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationKey(deviceId);
  const swrFn = getDeleteDeviceV1ApiDevicesDeviceIdDeletePostMutationFetcher(deviceId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get all configurations
 * @summary Get Configurations
 */
export const getConfigurationsV1ApiConfigurationsGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Config[]>(
    {url: `/v1/api/configurations`, method: 'GET'
    },
    options);
  }



export const getGetConfigurationsV1ApiConfigurationsGetKey = () => [`/v1/api/configurations`] as const;

export type GetConfigurationsV1ApiConfigurationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigurationsV1ApiConfigurationsGet>>>
export type GetConfigurationsV1ApiConfigurationsGetQueryError = unknown

/**
 * @summary Get Configurations
 */
export const useGetConfigurationsV1ApiConfigurationsGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConfigurationsV1ApiConfigurationsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConfigurationsV1ApiConfigurationsGetKey() : null);
  const swrFn = () => getConfigurationsV1ApiConfigurationsGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a new configuration
 * @summary Create Configuration
 */
export const createConfigurationV1ApiConfigurationsPost = (
    configCreate: ConfigCreate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Config>(
    {url: `/v1/api/configurations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configCreate
    },
    options);
  }



export const getCreateConfigurationV1ApiConfigurationsPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: ConfigCreate }) => {
    return createConfigurationV1ApiConfigurationsPost(arg, options);
  }
}
export const getCreateConfigurationV1ApiConfigurationsPostMutationKey = () => [`/v1/api/configurations`] as const;

export type CreateConfigurationV1ApiConfigurationsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createConfigurationV1ApiConfigurationsPost>>>
export type CreateConfigurationV1ApiConfigurationsPostMutationError = HTTPValidationError

/**
 * @summary Create Configuration
 */
export const useCreateConfigurationV1ApiConfigurationsPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createConfigurationV1ApiConfigurationsPost>>, TError, Key, ConfigCreate, Awaited<ReturnType<typeof createConfigurationV1ApiConfigurationsPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateConfigurationV1ApiConfigurationsPostMutationKey();
  const swrFn = getCreateConfigurationV1ApiConfigurationsPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get a specific configuration
 * @summary Get Configuration
 */
export const getConfigurationV1ApiConfigurationsConfigIdGet = (
    configId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Config>(
    {url: `/v1/api/configurations/${configId}`, method: 'GET'
    },
    options);
  }



export const getGetConfigurationV1ApiConfigurationsConfigIdGetKey = (configId: string,) => [`/v1/api/configurations/${configId}`] as const;

export type GetConfigurationV1ApiConfigurationsConfigIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigurationV1ApiConfigurationsConfigIdGet>>>
export type GetConfigurationV1ApiConfigurationsConfigIdGetQueryError = HTTPValidationError

/**
 * @summary Get Configuration
 */
export const useGetConfigurationV1ApiConfigurationsConfigIdGet = <TError = HTTPValidationError>(
  configId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConfigurationV1ApiConfigurationsConfigIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(configId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConfigurationV1ApiConfigurationsConfigIdGetKey(configId) : null);
  const swrFn = () => getConfigurationV1ApiConfigurationsConfigIdGet(configId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Edit an existing configuration
 * @summary Edit Configuration
 */
export const editConfigurationV1ApiConfigurationsConfigIdEditPost = (
    configId: string,
    configUpdate: ConfigUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Config>(
    {url: `/v1/api/configurations/${configId}/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: configUpdate
    },
    options);
  }



export const getEditConfigurationV1ApiConfigurationsConfigIdEditPostMutationFetcher = (configId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: ConfigUpdate }) => {
    return editConfigurationV1ApiConfigurationsConfigIdEditPost(configId, arg, options);
  }
}
export const getEditConfigurationV1ApiConfigurationsConfigIdEditPostMutationKey = (configId: string,) => [`/v1/api/configurations/${configId}/edit`] as const;

export type EditConfigurationV1ApiConfigurationsConfigIdEditPostMutationResult = NonNullable<Awaited<ReturnType<typeof editConfigurationV1ApiConfigurationsConfigIdEditPost>>>
export type EditConfigurationV1ApiConfigurationsConfigIdEditPostMutationError = HTTPValidationError

/**
 * @summary Edit Configuration
 */
export const useEditConfigurationV1ApiConfigurationsConfigIdEditPost = <TError = HTTPValidationError>(
  configId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof editConfigurationV1ApiConfigurationsConfigIdEditPost>>, TError, Key, ConfigUpdate, Awaited<ReturnType<typeof editConfigurationV1ApiConfigurationsConfigIdEditPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEditConfigurationV1ApiConfigurationsConfigIdEditPostMutationKey(configId);
  const swrFn = getEditConfigurationV1ApiConfigurationsConfigIdEditPostMutationFetcher(configId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Delete a configuration
 * @summary Delete Configuration
 */
export const deleteConfigurationV1ApiConfigurationsConfigIdDeletePost = (
    configId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/configurations/${configId}/delete`, method: 'POST'
    },
    options);
  }



export const getDeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationFetcher = (configId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteConfigurationV1ApiConfigurationsConfigIdDeletePost(configId, options);
  }
}
export const getDeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationKey = (configId: string,) => [`/v1/api/configurations/${configId}/delete`] as const;

export type DeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteConfigurationV1ApiConfigurationsConfigIdDeletePost>>>
export type DeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationError = HTTPValidationError

/**
 * @summary Delete Configuration
 */
export const useDeleteConfigurationV1ApiConfigurationsConfigIdDeletePost = <TError = HTTPValidationError>(
  configId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteConfigurationV1ApiConfigurationsConfigIdDeletePost>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteConfigurationV1ApiConfigurationsConfigIdDeletePost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationKey(configId);
  const swrFn = getDeleteConfigurationV1ApiConfigurationsConfigIdDeletePostMutationFetcher(configId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Get Configuration Traces
 */
export const getConfigurationTracesV1ApiConfigurationsConfigIdTracesGet = (
    configId: string,
    params?: GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<SrcApiConfigurationsTraceWithDevice[]>(
    {url: `/v1/api/configurations/${configId}/traces`, method: 'GET',
        params
    },
    options);
  }



export const getGetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetKey = (configId: string,
    params?: GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetParams,) => [`/v1/api/configurations/${configId}/traces`, ...(params ? [params]: [])] as const;

export type GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigurationTracesV1ApiConfigurationsConfigIdTracesGet>>>
export type GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetQueryError = HTTPValidationError

/**
 * @summary Get Configuration Traces
 */
export const useGetConfigurationTracesV1ApiConfigurationsConfigIdTracesGet = <TError = HTTPValidationError>(
  configId: string,
    params?: GetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConfigurationTracesV1ApiConfigurationsConfigIdTracesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(configId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConfigurationTracesV1ApiConfigurationsConfigIdTracesGetKey(configId,params) : null);
  const swrFn = () => getConfigurationTracesV1ApiConfigurationsConfigIdTracesGet(configId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get all traces with filtering and sorting
 * @summary Get Traces
 */
export const getTracesV1ApiTracesGet = (
    params?: GetTracesV1ApiTracesGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<SrcApiTracesTraceWithDevice[]>(
    {url: `/v1/api/traces`, method: 'GET',
        params
    },
    options);
  }



export const getGetTracesV1ApiTracesGetKey = (params?: GetTracesV1ApiTracesGetParams,) => [`/v1/api/traces`, ...(params ? [params]: [])] as const;

export type GetTracesV1ApiTracesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTracesV1ApiTracesGet>>>
export type GetTracesV1ApiTracesGetQueryError = HTTPValidationError

/**
 * @summary Get Traces
 */
export const useGetTracesV1ApiTracesGet = <TError = HTTPValidationError>(
  params?: GetTracesV1ApiTracesGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTracesV1ApiTracesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTracesV1ApiTracesGetKey(params) : null);
  const swrFn = () => getTracesV1ApiTracesGet(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create/upload a new trace. Accepts form-data with a file upload and metadata.

This endpoint is intentionally implemented with Form and File parameters
to ensure full OpenAPI compatibility for auto-generated clients on the frontend.
 * @summary Create Trace
 */
export const createTraceV1ApiTracesPost = (
    bodyCreateTraceV1ApiTracesPost: BodyCreateTraceV1ApiTracesPost,
 options?: SecondParameter<typeof axiosInstance>) => {const formData = new FormData();
formData.append(`trace_name`, bodyCreateTraceV1ApiTracesPost.trace_name)
formData.append(`trace_file`, bodyCreateTraceV1ApiTracesPost.trace_file)
formData.append(`trace_timestamp`, bodyCreateTraceV1ApiTracesPost.trace_timestamp)
if(bodyCreateTraceV1ApiTracesPost.configuration_id !== undefined && bodyCreateTraceV1ApiTracesPost.configuration_id !== null) {
 formData.append(`configuration_id`, bodyCreateTraceV1ApiTracesPost.configuration_id)
 }
if(bodyCreateTraceV1ApiTracesPost.device_id !== undefined && bodyCreateTraceV1ApiTracesPost.device_id !== null) {
 formData.append(`device_id`, bodyCreateTraceV1ApiTracesPost.device_id)
 }

    return axiosInstance<TraceDetail>(
    {url: `/v1/api/traces`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
    options);
  }



export const getCreateTraceV1ApiTracesPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: BodyCreateTraceV1ApiTracesPost }) => {
    return createTraceV1ApiTracesPost(arg, options);
  }
}
export const getCreateTraceV1ApiTracesPostMutationKey = () => [`/v1/api/traces`] as const;

export type CreateTraceV1ApiTracesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTraceV1ApiTracesPost>>>
export type CreateTraceV1ApiTracesPostMutationError = HTTPValidationError

/**
 * @summary Create Trace
 */
export const useCreateTraceV1ApiTracesPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTraceV1ApiTracesPost>>, TError, Key, BodyCreateTraceV1ApiTracesPost, Awaited<ReturnType<typeof createTraceV1ApiTracesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTraceV1ApiTracesPostMutationKey();
  const swrFn = getCreateTraceV1ApiTracesPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get a specific trace
 * @summary Get Trace
 */
export const getTraceV1ApiTracesTraceIdGet = (
    traceId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<TraceDetail>(
    {url: `/v1/api/traces/${traceId}`, method: 'GET'
    },
    options);
  }



export const getGetTraceV1ApiTracesTraceIdGetKey = (traceId: string,) => [`/v1/api/traces/${traceId}`] as const;

export type GetTraceV1ApiTracesTraceIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTraceV1ApiTracesTraceIdGet>>>
export type GetTraceV1ApiTracesTraceIdGetQueryError = HTTPValidationError

/**
 * @summary Get Trace
 */
export const useGetTraceV1ApiTracesTraceIdGet = <TError = HTTPValidationError>(
  traceId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTraceV1ApiTracesTraceIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(traceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTraceV1ApiTracesTraceIdGetKey(traceId) : null);
  const swrFn = () => getTraceV1ApiTracesTraceIdGet(traceId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Edit trace metadata
 * @summary Edit Trace
 */
export const editTraceV1ApiTracesTraceIdEditPost = (
    traceId: string,
    traceUpdate: TraceUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<TraceDetail>(
    {url: `/v1/api/traces/${traceId}/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: traceUpdate
    },
    options);
  }



export const getEditTraceV1ApiTracesTraceIdEditPostMutationFetcher = (traceId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: TraceUpdate }) => {
    return editTraceV1ApiTracesTraceIdEditPost(traceId, arg, options);
  }
}
export const getEditTraceV1ApiTracesTraceIdEditPostMutationKey = (traceId: string,) => [`/v1/api/traces/${traceId}/edit`] as const;

export type EditTraceV1ApiTracesTraceIdEditPostMutationResult = NonNullable<Awaited<ReturnType<typeof editTraceV1ApiTracesTraceIdEditPost>>>
export type EditTraceV1ApiTracesTraceIdEditPostMutationError = HTTPValidationError

/**
 * @summary Edit Trace
 */
export const useEditTraceV1ApiTracesTraceIdEditPost = <TError = HTTPValidationError>(
  traceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof editTraceV1ApiTracesTraceIdEditPost>>, TError, Key, TraceUpdate, Awaited<ReturnType<typeof editTraceV1ApiTracesTraceIdEditPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEditTraceV1ApiTracesTraceIdEditPostMutationKey(traceId);
  const swrFn = getEditTraceV1ApiTracesTraceIdEditPostMutationFetcher(traceId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Delete a trace
 * @summary Delete Trace
 */
export const deleteTraceV1ApiTracesTraceIdDeletePost = (
    traceId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/traces/${traceId}/delete`, method: 'POST'
    },
    options);
  }



export const getDeleteTraceV1ApiTracesTraceIdDeletePostMutationFetcher = (traceId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteTraceV1ApiTracesTraceIdDeletePost(traceId, options);
  }
}
export const getDeleteTraceV1ApiTracesTraceIdDeletePostMutationKey = (traceId: string,) => [`/v1/api/traces/${traceId}/delete`] as const;

export type DeleteTraceV1ApiTracesTraceIdDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTraceV1ApiTracesTraceIdDeletePost>>>
export type DeleteTraceV1ApiTracesTraceIdDeletePostMutationError = HTTPValidationError

/**
 * @summary Delete Trace
 */
export const useDeleteTraceV1ApiTracesTraceIdDeletePost = <TError = HTTPValidationError>(
  traceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteTraceV1ApiTracesTraceIdDeletePost>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteTraceV1ApiTracesTraceIdDeletePost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteTraceV1ApiTracesTraceIdDeletePostMutationKey(traceId);
  const swrFn = getDeleteTraceV1ApiTracesTraceIdDeletePostMutationFetcher(traceId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get all queries
 * @summary Get Queries
 */
export const getQueriesV1ApiQueriesGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Query[]>(
    {url: `/v1/api/queries`, method: 'GET'
    },
    options);
  }



export const getGetQueriesV1ApiQueriesGetKey = () => [`/v1/api/queries`] as const;

export type GetQueriesV1ApiQueriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQueriesV1ApiQueriesGet>>>
export type GetQueriesV1ApiQueriesGetQueryError = unknown

/**
 * @summary Get Queries
 */
export const useGetQueriesV1ApiQueriesGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getQueriesV1ApiQueriesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetQueriesV1ApiQueriesGetKey() : null);
  const swrFn = () => getQueriesV1ApiQueriesGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a new query
 * @summary Create Query
 */
export const createQueryV1ApiQueriesPost = (
    queryCreate: QueryCreate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Query>(
    {url: `/v1/api/queries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryCreate
    },
    options);
  }



export const getCreateQueryV1ApiQueriesPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: QueryCreate }) => {
    return createQueryV1ApiQueriesPost(arg, options);
  }
}
export const getCreateQueryV1ApiQueriesPostMutationKey = () => [`/v1/api/queries`] as const;

export type CreateQueryV1ApiQueriesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createQueryV1ApiQueriesPost>>>
export type CreateQueryV1ApiQueriesPostMutationError = HTTPValidationError

/**
 * @summary Create Query
 */
export const useCreateQueryV1ApiQueriesPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createQueryV1ApiQueriesPost>>, TError, Key, QueryCreate, Awaited<ReturnType<typeof createQueryV1ApiQueriesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateQueryV1ApiQueriesPostMutationKey();
  const swrFn = getCreateQueryV1ApiQueriesPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get a specific query
 * @summary Get Query
 */
export const getQueryV1ApiQueriesQueryIdGet = (
    queryId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Query>(
    {url: `/v1/api/queries/${queryId}`, method: 'GET'
    },
    options);
  }



export const getGetQueryV1ApiQueriesQueryIdGetKey = (queryId: string,) => [`/v1/api/queries/${queryId}`] as const;

export type GetQueryV1ApiQueriesQueryIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryV1ApiQueriesQueryIdGet>>>
export type GetQueryV1ApiQueriesQueryIdGetQueryError = HTTPValidationError

/**
 * @summary Get Query
 */
export const useGetQueryV1ApiQueriesQueryIdGet = <TError = HTTPValidationError>(
  queryId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getQueryV1ApiQueriesQueryIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetQueryV1ApiQueriesQueryIdGetKey(queryId) : null);
  const swrFn = () => getQueryV1ApiQueriesQueryIdGet(queryId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Edit an existing query
 * @summary Edit Query
 */
export const editQueryV1ApiQueriesQueryIdEditPost = (
    queryId: string,
    queryUpdate: QueryUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<Query>(
    {url: `/v1/api/queries/${queryId}/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: queryUpdate
    },
    options);
  }



export const getEditQueryV1ApiQueriesQueryIdEditPostMutationFetcher = (queryId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: QueryUpdate }) => {
    return editQueryV1ApiQueriesQueryIdEditPost(queryId, arg, options);
  }
}
export const getEditQueryV1ApiQueriesQueryIdEditPostMutationKey = (queryId: string,) => [`/v1/api/queries/${queryId}/edit`] as const;

export type EditQueryV1ApiQueriesQueryIdEditPostMutationResult = NonNullable<Awaited<ReturnType<typeof editQueryV1ApiQueriesQueryIdEditPost>>>
export type EditQueryV1ApiQueriesQueryIdEditPostMutationError = HTTPValidationError

/**
 * @summary Edit Query
 */
export const useEditQueryV1ApiQueriesQueryIdEditPost = <TError = HTTPValidationError>(
  queryId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof editQueryV1ApiQueriesQueryIdEditPost>>, TError, Key, QueryUpdate, Awaited<ReturnType<typeof editQueryV1ApiQueriesQueryIdEditPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEditQueryV1ApiQueriesQueryIdEditPostMutationKey(queryId);
  const swrFn = getEditQueryV1ApiQueriesQueryIdEditPostMutationFetcher(queryId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Delete a query
 * @summary Delete Query
 */
export const deleteQueryV1ApiQueriesQueryIdDeletePost = (
    queryId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/queries/${queryId}/delete`, method: 'POST'
    },
    options);
  }



export const getDeleteQueryV1ApiQueriesQueryIdDeletePostMutationFetcher = (queryId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteQueryV1ApiQueriesQueryIdDeletePost(queryId, options);
  }
}
export const getDeleteQueryV1ApiQueriesQueryIdDeletePostMutationKey = (queryId: string,) => [`/v1/api/queries/${queryId}/delete`] as const;

export type DeleteQueryV1ApiQueriesQueryIdDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQueryV1ApiQueriesQueryIdDeletePost>>>
export type DeleteQueryV1ApiQueriesQueryIdDeletePostMutationError = HTTPValidationError

/**
 * @summary Delete Query
 */
export const useDeleteQueryV1ApiQueriesQueryIdDeletePost = <TError = HTTPValidationError>(
  queryId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteQueryV1ApiQueriesQueryIdDeletePost>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteQueryV1ApiQueriesQueryIdDeletePost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteQueryV1ApiQueriesQueryIdDeletePostMutationKey(queryId);
  const swrFn = getDeleteQueryV1ApiQueriesQueryIdDeletePostMutationFetcher(queryId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Export query results in various formats
 * @summary Export Result
 */
export const exportResultV1ApiResultsTraceIdQueryIdExportGet = (
    traceId: string,
    queryId: string,
    params: ExportResultV1ApiResultsTraceIdQueryIdExportGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/results/${traceId}/${queryId}/export`, method: 'GET',
        params
    },
    options);
  }



export const getExportResultV1ApiResultsTraceIdQueryIdExportGetKey = (traceId: string,
    queryId: string,
    params: ExportResultV1ApiResultsTraceIdQueryIdExportGetParams,) => [`/v1/api/results/${traceId}/${queryId}/export`, ...(params ? [params]: [])] as const;

export type ExportResultV1ApiResultsTraceIdQueryIdExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportResultV1ApiResultsTraceIdQueryIdExportGet>>>
export type ExportResultV1ApiResultsTraceIdQueryIdExportGetQueryError = HTTPValidationError

/**
 * @summary Export Result
 */
export const useExportResultV1ApiResultsTraceIdQueryIdExportGet = <TError = HTTPValidationError>(
  traceId: string,
    queryId: string,
    params: ExportResultV1ApiResultsTraceIdQueryIdExportGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof exportResultV1ApiResultsTraceIdQueryIdExportGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(traceId && queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getExportResultV1ApiResultsTraceIdQueryIdExportGetKey(traceId,queryId,params) : null);
  const swrFn = () => exportResultV1ApiResultsTraceIdQueryIdExportGet(traceId,queryId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get query results formatted for DataTables
 * @summary Get Datatables Result
 */
export const getDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGet = (
    traceId: string,
    queryId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/results/${traceId}/${queryId}/datatables`, method: 'GET'
    },
    options);
  }



export const getGetDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGetKey = (traceId: string,
    queryId: string,) => [`/v1/api/results/${traceId}/${queryId}/datatables`] as const;

export type GetDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGet>>>
export type GetDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGetQueryError = HTTPValidationError

/**
 * @summary Get Datatables Result
 */
export const useGetDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGet = <TError = HTTPValidationError>(
  traceId: string,
    queryId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(traceId && queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGetKey(traceId,queryId) : null);
  const swrFn = () => getDatatablesResultV1ApiResultsTraceIdQueryIdDatatablesGet(traceId,queryId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get query results as JSON
 * @summary Get Json Result
 */
export const getJsonResultV1ApiResultsTraceIdQueryIdJsonGet = (
    traceId: string,
    queryId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/results/${traceId}/${queryId}/json`, method: 'GET'
    },
    options);
  }



export const getGetJsonResultV1ApiResultsTraceIdQueryIdJsonGetKey = (traceId: string,
    queryId: string,) => [`/v1/api/results/${traceId}/${queryId}/json`] as const;

export type GetJsonResultV1ApiResultsTraceIdQueryIdJsonGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJsonResultV1ApiResultsTraceIdQueryIdJsonGet>>>
export type GetJsonResultV1ApiResultsTraceIdQueryIdJsonGetQueryError = HTTPValidationError

/**
 * @summary Get Json Result
 */
export const useGetJsonResultV1ApiResultsTraceIdQueryIdJsonGet = <TError = HTTPValidationError>(
  traceId: string,
    queryId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getJsonResultV1ApiResultsTraceIdQueryIdJsonGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(traceId && queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetJsonResultV1ApiResultsTraceIdQueryIdJsonGetKey(traceId,queryId) : null);
  const swrFn = () => getJsonResultV1ApiResultsTraceIdQueryIdJsonGet(traceId,queryId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a new job request
 * @summary Create Job Request
 */
export const createJobRequestV1ApiRequestsPost = (
    jobRequestCreate: JobRequestCreate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<JobRequestResponse>(
    {url: `/v1/api/requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobRequestCreate
    },
    options);
  }



export const getCreateJobRequestV1ApiRequestsPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: JobRequestCreate }) => {
    return createJobRequestV1ApiRequestsPost(arg, options);
  }
}
export const getCreateJobRequestV1ApiRequestsPostMutationKey = () => [`/v1/api/requests`] as const;

export type CreateJobRequestV1ApiRequestsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createJobRequestV1ApiRequestsPost>>>
export type CreateJobRequestV1ApiRequestsPostMutationError = HTTPValidationError

/**
 * @summary Create Job Request
 */
export const useCreateJobRequestV1ApiRequestsPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createJobRequestV1ApiRequestsPost>>, TError, Key, JobRequestCreate, Awaited<ReturnType<typeof createJobRequestV1ApiRequestsPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateJobRequestV1ApiRequestsPostMutationKey();
  const swrFn = getCreateJobRequestV1ApiRequestsPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get job request details
 * @summary Get Job Request
 */
export const getJobRequestV1ApiRequestsJobIdGet = (
    jobId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<JobRequestResponse>(
    {url: `/v1/api/requests/${jobId}`, method: 'GET'
    },
    options);
  }



export const getGetJobRequestV1ApiRequestsJobIdGetKey = (jobId: string,) => [`/v1/api/requests/${jobId}`] as const;

export type GetJobRequestV1ApiRequestsJobIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJobRequestV1ApiRequestsJobIdGet>>>
export type GetJobRequestV1ApiRequestsJobIdGetQueryError = HTTPValidationError

/**
 * @summary Get Job Request
 */
export const useGetJobRequestV1ApiRequestsJobIdGet = <TError = HTTPValidationError>(
  jobId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getJobRequestV1ApiRequestsJobIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(jobId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetJobRequestV1ApiRequestsJobIdGetKey(jobId) : null);
  const swrFn = () => getJobRequestV1ApiRequestsJobIdGet(jobId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Server-Sent Events stream for job updates
 * @summary Stream Job Updates
 */
export const streamJobUpdatesV1ApiRequestsJobIdStreamGet = (
    jobId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/requests/${jobId}/stream`, method: 'GET'
    },
    options);
  }



export const getStreamJobUpdatesV1ApiRequestsJobIdStreamGetKey = (jobId: string,) => [`/v1/api/requests/${jobId}/stream`] as const;

export type StreamJobUpdatesV1ApiRequestsJobIdStreamGetQueryResult = NonNullable<Awaited<ReturnType<typeof streamJobUpdatesV1ApiRequestsJobIdStreamGet>>>
export type StreamJobUpdatesV1ApiRequestsJobIdStreamGetQueryError = HTTPValidationError

/**
 * @summary Stream Job Updates
 */
export const useStreamJobUpdatesV1ApiRequestsJobIdStreamGet = <TError = HTTPValidationError>(
  jobId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof streamJobUpdatesV1ApiRequestsJobIdStreamGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(jobId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getStreamJobUpdatesV1ApiRequestsJobIdStreamGetKey(jobId) : null);
  const swrFn = () => streamJobUpdatesV1ApiRequestsJobIdStreamGet(jobId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Export query results in various formats
 * @summary Export Result
 */
export const exportResultV1ApiGroupResultsQueryIdExportGet = (
    queryId: string,
    params: ExportResultV1ApiGroupResultsQueryIdExportGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/group_results/${queryId}/export`, method: 'GET',
        params
    },
    options);
  }



export const getExportResultV1ApiGroupResultsQueryIdExportGetKey = (queryId: string,
    params: ExportResultV1ApiGroupResultsQueryIdExportGetParams,) => [`/v1/api/group_results/${queryId}/export`, ...(params ? [params]: [])] as const;

export type ExportResultV1ApiGroupResultsQueryIdExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportResultV1ApiGroupResultsQueryIdExportGet>>>
export type ExportResultV1ApiGroupResultsQueryIdExportGetQueryError = HTTPValidationError

/**
 * @summary Export Result
 */
export const useExportResultV1ApiGroupResultsQueryIdExportGet = <TError = HTTPValidationError>(
  queryId: string,
    params: ExportResultV1ApiGroupResultsQueryIdExportGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof exportResultV1ApiGroupResultsQueryIdExportGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getExportResultV1ApiGroupResultsQueryIdExportGetKey(queryId,params) : null);
  const swrFn = () => exportResultV1ApiGroupResultsQueryIdExportGet(queryId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get query results formatted for DataTables
 * @summary Get Datatables Result
 */
export const getDatatablesResultV1ApiGroupResultsQueryIdDatatablesGet = (
    queryId: string,
    params: GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/group_results/${queryId}/datatables`, method: 'GET',
        params
    },
    options);
  }



export const getGetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetKey = (queryId: string,
    params: GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetParams,) => [`/v1/api/group_results/${queryId}/datatables`, ...(params ? [params]: [])] as const;

export type GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDatatablesResultV1ApiGroupResultsQueryIdDatatablesGet>>>
export type GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetQueryError = HTTPValidationError

/**
 * @summary Get Datatables Result
 */
export const useGetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGet = <TError = HTTPValidationError>(
  queryId: string,
    params: GetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDatatablesResultV1ApiGroupResultsQueryIdDatatablesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDatatablesResultV1ApiGroupResultsQueryIdDatatablesGetKey(queryId,params) : null);
  const swrFn = () => getDatatablesResultV1ApiGroupResultsQueryIdDatatablesGet(queryId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get query results as JSON
 * @summary Get Json Result
 */
export const getJsonResultV1ApiGroupResultsQueryIdJsonGet = (
    queryId: string,
    params: GetJsonResultV1ApiGroupResultsQueryIdJsonGetParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/group_results/${queryId}/json`, method: 'GET',
        params
    },
    options);
  }



export const getGetJsonResultV1ApiGroupResultsQueryIdJsonGetKey = (queryId: string,
    params: GetJsonResultV1ApiGroupResultsQueryIdJsonGetParams,) => [`/v1/api/group_results/${queryId}/json`, ...(params ? [params]: [])] as const;

export type GetJsonResultV1ApiGroupResultsQueryIdJsonGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJsonResultV1ApiGroupResultsQueryIdJsonGet>>>
export type GetJsonResultV1ApiGroupResultsQueryIdJsonGetQueryError = HTTPValidationError

/**
 * @summary Get Json Result
 */
export const useGetJsonResultV1ApiGroupResultsQueryIdJsonGet = <TError = HTTPValidationError>(
  queryId: string,
    params: GetJsonResultV1ApiGroupResultsQueryIdJsonGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getJsonResultV1ApiGroupResultsQueryIdJsonGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(queryId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetJsonResultV1ApiGroupResultsQueryIdJsonGetKey(queryId,params) : null);
  const swrFn = () => getJsonResultV1ApiGroupResultsQueryIdJsonGet(queryId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Fetch pending job-device pairs for worker processing.
 * @summary Get Pending Jobs
 */
export const getPendingJobsV1ApiWorkerJobsPendingGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<PendingJob[]>(
    {url: `/v1/api/worker/jobs/pending`, method: 'GET'
    },
    options);
  }



export const getGetPendingJobsV1ApiWorkerJobsPendingGetKey = () => [`/v1/api/worker/jobs/pending`] as const;

export type GetPendingJobsV1ApiWorkerJobsPendingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingJobsV1ApiWorkerJobsPendingGet>>>
export type GetPendingJobsV1ApiWorkerJobsPendingGetQueryError = HTTPValidationError

/**
 * @summary Get Pending Jobs
 */
export const useGetPendingJobsV1ApiWorkerJobsPendingGet = <TError = HTTPValidationError>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getPendingJobsV1ApiWorkerJobsPendingGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetPendingJobsV1ApiWorkerJobsPendingGetKey() : null);
  const swrFn = () => getPendingJobsV1ApiWorkerJobsPendingGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Fetch configuration by ID.
 * @summary Get Config
 */
export const getConfigV1ApiWorkerConfigsConfigIdGet = (
    configId: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<ConfigResponse>(
    {url: `/v1/api/worker/configs/${configId}`, method: 'GET'
    },
    options);
  }



export const getGetConfigV1ApiWorkerConfigsConfigIdGetKey = (configId: string,) => [`/v1/api/worker/configs/${configId}`] as const;

export type GetConfigV1ApiWorkerConfigsConfigIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigV1ApiWorkerConfigsConfigIdGet>>>
export type GetConfigV1ApiWorkerConfigsConfigIdGetQueryError = HTTPValidationError

/**
 * @summary Get Config
 */
export const useGetConfigV1ApiWorkerConfigsConfigIdGet = <TError = HTTPValidationError>(
  configId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getConfigV1ApiWorkerConfigsConfigIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(configId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetConfigV1ApiWorkerConfigsConfigIdGetKey(configId) : null);
  const swrFn = () => getConfigV1ApiWorkerConfigsConfigIdGet(configId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Fetch device by serial (device_uuid or device_id).
 * @summary Get Device By Serial
 */
export const getDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGet = (
    deviceSerial: string,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<DeviceResponse>(
    {url: `/v1/api/worker/devices/by-serial/${deviceSerial}`, method: 'GET'
    },
    options);
  }



export const getGetDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGetKey = (deviceSerial: string,) => [`/v1/api/worker/devices/by-serial/${deviceSerial}`] as const;

export type GetDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGet>>>
export type GetDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGetQueryError = HTTPValidationError

/**
 * @summary Get Device By Serial
 */
export const useGetDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGet = <TError = HTTPValidationError>(
  deviceSerial: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(deviceSerial)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGetKey(deviceSerial) : null);
  const swrFn = () => getDeviceBySerialV1ApiWorkerDevicesBySerialDeviceSerialGet(deviceSerial, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Fetch all devices.
 * @summary Get Devices
 */
export const getDevicesV1ApiWorkerDevicesGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/devices`, method: 'GET'
    },
    options);
  }



export const getGetDevicesV1ApiWorkerDevicesGetKey = () => [`/v1/api/worker/devices`] as const;

export type GetDevicesV1ApiWorkerDevicesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDevicesV1ApiWorkerDevicesGet>>>
export type GetDevicesV1ApiWorkerDevicesGetQueryError = HTTPValidationError

/**
 * @summary Get Devices
 */
export const useGetDevicesV1ApiWorkerDevicesGet = <TError = HTTPValidationError>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDevicesV1ApiWorkerDevicesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDevicesV1ApiWorkerDevicesGetKey() : null);
  const swrFn = () => getDevicesV1ApiWorkerDevicesGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a new device.
 * @summary Create Device
 */
export const createDeviceV1ApiWorkerDevicesPost = (
    deviceCreateRequest: DeviceCreateRequest,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/devices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceCreateRequest
    },
    options);
  }



export const getCreateDeviceV1ApiWorkerDevicesPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: DeviceCreateRequest }) => {
    return createDeviceV1ApiWorkerDevicesPost(arg, options);
  }
}
export const getCreateDeviceV1ApiWorkerDevicesPostMutationKey = () => [`/v1/api/worker/devices`] as const;

export type CreateDeviceV1ApiWorkerDevicesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDeviceV1ApiWorkerDevicesPost>>>
export type CreateDeviceV1ApiWorkerDevicesPostMutationError = HTTPValidationError

/**
 * @summary Create Device
 */
export const useCreateDeviceV1ApiWorkerDevicesPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createDeviceV1ApiWorkerDevicesPost>>, TError, Key, DeviceCreateRequest, Awaited<ReturnType<typeof createDeviceV1ApiWorkerDevicesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateDeviceV1ApiWorkerDevicesPostMutationKey();
  const swrFn = getCreateDeviceV1ApiWorkerDevicesPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Update an existing device.
 * @summary Update Device
 */
export const updateDeviceV1ApiWorkerDevicesDeviceIdPut = (
    deviceId: string,
    deviceUpdateRequest: DeviceUpdateRequest,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/devices/${deviceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: deviceUpdateRequest
    },
    options);
  }



export const getUpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationFetcher = (deviceId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: DeviceUpdateRequest }) => {
    return updateDeviceV1ApiWorkerDevicesDeviceIdPut(deviceId, arg, options);
  }
}
export const getUpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationKey = (deviceId: string,) => [`/v1/api/worker/devices/${deviceId}`] as const;

export type UpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateDeviceV1ApiWorkerDevicesDeviceIdPut>>>
export type UpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationError = HTTPValidationError

/**
 * @summary Update Device
 */
export const useUpdateDeviceV1ApiWorkerDevicesDeviceIdPut = <TError = HTTPValidationError>(
  deviceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateDeviceV1ApiWorkerDevicesDeviceIdPut>>, TError, Key, DeviceUpdateRequest, Awaited<ReturnType<typeof updateDeviceV1ApiWorkerDevicesDeviceIdPut>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationKey(deviceId);
  const swrFn = getUpdateDeviceV1ApiWorkerDevicesDeviceIdPutMutationFetcher(deviceId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Create a trace record.
 * @summary Create Trace
 */
export const createTraceV1ApiWorkerTracesPost = (
    traceCreateRequest: TraceCreateRequest,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<TraceCreateResponse>(
    {url: `/v1/api/worker/traces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: traceCreateRequest
    },
    options);
  }



export const getCreateTraceV1ApiWorkerTracesPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: TraceCreateRequest }) => {
    return createTraceV1ApiWorkerTracesPost(arg, options);
  }
}
export const getCreateTraceV1ApiWorkerTracesPostMutationKey = () => [`/v1/api/worker/traces`] as const;

export type CreateTraceV1ApiWorkerTracesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTraceV1ApiWorkerTracesPost>>>
export type CreateTraceV1ApiWorkerTracesPostMutationError = HTTPValidationError

/**
 * @summary Create Trace
 */
export const useCreateTraceV1ApiWorkerTracesPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTraceV1ApiWorkerTracesPost>>, TError, Key, TraceCreateRequest, Awaited<ReturnType<typeof createTraceV1ApiWorkerTracesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTraceV1ApiWorkerTracesPostMutationKey();
  const swrFn = getCreateTraceV1ApiWorkerTracesPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Update job status.
 * @summary Update Job Status
 */
export const updateJobStatusV1ApiWorkerJobsJobIdStatusPost = (
    jobId: string,
    jobStatusUpdate: JobStatusUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/jobs/${jobId}/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobStatusUpdate
    },
    options);
  }



export const getUpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationFetcher = (jobId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: JobStatusUpdate }) => {
    return updateJobStatusV1ApiWorkerJobsJobIdStatusPost(jobId, arg, options);
  }
}
export const getUpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationKey = (jobId: string,) => [`/v1/api/worker/jobs/${jobId}/status`] as const;

export type UpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationResult = NonNullable<Awaited<ReturnType<typeof updateJobStatusV1ApiWorkerJobsJobIdStatusPost>>>
export type UpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationError = HTTPValidationError

/**
 * @summary Update Job Status
 */
export const useUpdateJobStatusV1ApiWorkerJobsJobIdStatusPost = <TError = HTTPValidationError>(
  jobId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateJobStatusV1ApiWorkerJobsJobIdStatusPost>>, TError, Key, JobStatusUpdate, Awaited<ReturnType<typeof updateJobStatusV1ApiWorkerJobsJobIdStatusPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationKey(jobId);
  const swrFn = getUpdateJobStatusV1ApiWorkerJobsJobIdStatusPostMutationFetcher(jobId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Record a job progress update for a specific device.
 * @summary Add Job Update
 */
export const addJobUpdateV1ApiWorkerJobsJobIdUpdatesPost = (
    jobId: string,
    jobProgressUpdate: JobProgressUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/jobs/${jobId}/updates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobProgressUpdate
    },
    options);
  }



export const getAddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationFetcher = (jobId: string, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: JobProgressUpdate }) => {
    return addJobUpdateV1ApiWorkerJobsJobIdUpdatesPost(jobId, arg, options);
  }
}
export const getAddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationKey = (jobId: string,) => [`/v1/api/worker/jobs/${jobId}/updates`] as const;

export type AddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationResult = NonNullable<Awaited<ReturnType<typeof addJobUpdateV1ApiWorkerJobsJobIdUpdatesPost>>>
export type AddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationError = HTTPValidationError

/**
 * @summary Add Job Update
 */
export const useAddJobUpdateV1ApiWorkerJobsJobIdUpdatesPost = <TError = HTTPValidationError>(
  jobId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addJobUpdateV1ApiWorkerJobsJobIdUpdatesPost>>, TError, Key, JobProgressUpdate, Awaited<ReturnType<typeof addJobUpdateV1ApiWorkerJobsJobIdUpdatesPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationKey(jobId);
  const swrFn = getAddJobUpdateV1ApiWorkerJobsJobIdUpdatesPostMutationFetcher(jobId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Update the status of a specific job-device pair.
 * @summary Update Job Device Status
 */
export const updateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost = (
    jobDeviceStatusUpdate: JobDeviceStatusUpdate,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/job-devices/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobDeviceStatusUpdate
    },
    options);
  }



export const getUpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationFetcher = ( options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, { arg }: { arg: JobDeviceStatusUpdate }) => {
    return updateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost(arg, options);
  }
}
export const getUpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationKey = () => [`/v1/api/worker/job-devices/status`] as const;

export type UpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationResult = NonNullable<Awaited<ReturnType<typeof updateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost>>>
export type UpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationError = HTTPValidationError

/**
 * @summary Update Job Device Status
 */
export const useUpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost = <TError = HTTPValidationError>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost>>, TError, Key, JobDeviceStatusUpdate, Awaited<ReturnType<typeof updateJobDeviceStatusV1ApiWorkerJobDevicesStatusPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationKey();
  const swrFn = getUpdateJobDeviceStatusV1ApiWorkerJobDevicesStatusPostMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Upload a file to MinIO storage.

The file bytes should be sent as the raw request body.
Query params: bucket, object_name
 * @summary Upload File
 */
export const uploadFileV1ApiWorkerStorageUploadPost = (
    params: UploadFileV1ApiWorkerStorageUploadPostParams,
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<unknown>(
    {url: `/v1/api/worker/storage/upload`, method: 'POST',
        params
    },
    options);
  }



export const getUploadFileV1ApiWorkerStorageUploadPostMutationFetcher = (params: UploadFileV1ApiWorkerStorageUploadPostParams, options?: SecondParameter<typeof axiosInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return uploadFileV1ApiWorkerStorageUploadPost(params, options);
  }
}
export const getUploadFileV1ApiWorkerStorageUploadPostMutationKey = (params: UploadFileV1ApiWorkerStorageUploadPostParams,) => [`/v1/api/worker/storage/upload`, ...(params ? [params]: [])] as const;

export type UploadFileV1ApiWorkerStorageUploadPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFileV1ApiWorkerStorageUploadPost>>>
export type UploadFileV1ApiWorkerStorageUploadPostMutationError = HTTPValidationError

/**
 * @summary Upload File
 */
export const useUploadFileV1ApiWorkerStorageUploadPost = <TError = HTTPValidationError>(
  params: UploadFileV1ApiWorkerStorageUploadPostParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof uploadFileV1ApiWorkerStorageUploadPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof uploadFileV1ApiWorkerStorageUploadPost>>> & { swrKey?: string }, request?: SecondParameter<typeof axiosInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUploadFileV1ApiWorkerStorageUploadPostMutationKey(params);
  const swrFn = getUploadFileV1ApiWorkerStorageUploadPostMutationFetcher(params, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Read Root
 */
export const readRootGet = (
    
 options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<string>(
    {url: `/`, method: 'GET'
    },
    options);
  }



export const getReadRootGetKey = () => [`/`] as const;

export type ReadRootGetQueryResult = NonNullable<Awaited<ReturnType<typeof readRootGet>>>
export type ReadRootGetQueryError = unknown

/**
 * @summary Read Root
 */
export const useReadRootGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof readRootGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof axiosInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getReadRootGetKey() : null);
  const swrFn = () => readRootGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
