import { Button } from "@heroui/react"
import {
	deleteTraceV1ApiTracesTraceIdDeletePost,
	useGetTraceV1ApiTracesTraceIdGet,
} from "../../api/api-client"
import { InlineQueries } from "../../components/InlineQueries"
import { Layout } from "../../components/Layout"
import { toTitleCase } from "../../utils/humanize"
import { autoToast } from "../../components/toast"
import { useLocation } from "wouter"
import { QueryResult } from "../../components/QueryResult"
import { useState } from "react"
import type { Query } from "../../api/schemas"

const API_BASE_URL = import.meta.env.VITE_PUBLIC_API_URL || "http://localhost:8000"

export default function TracesViewPage({ id }: { id: string }) {
	const { data: trace, isLoading } = useGetTraceV1ApiTracesTraceIdGet(id)
	const [chosenQuery, setChosenQuery] = useState<Query | null>(null)
	const [, navigate] = useLocation()

	async function handleDelete() {
		const confirmed = window.confirm(
			"Are you sure you want to delete this trace? This action cannot be undone."
		)
		if (!confirmed) return

		await autoToast(deleteTraceV1ApiTracesTraceIdDeletePost(id), {
			loadingText: "Deleting trace...",
			successText: "Trace deleted!",
			errorText: "Failed to delete trace.",
		})

		navigate("/traces")
	}

	if (isLoading)
		return (
			<Layout>
				<p>Loading trace...</p>
			</Layout>
		)

	if (!trace)
		return (
			<Layout>
				<p>Trace not found!</p>
			</Layout>
		)

	const isSimpleperf = trace.configuration_type === "simpleperf"
	const isPerfetto = !trace.configuration_type || trace.configuration_type === "perfetto"
	const hasHtmlReport = !!trace.trace_html_filename

	const handleDownloadReport = () => {
		const downloadUrl = `${API_BASE_URL}/v1/api/traces/${trace.trace_id}/html-report-download`
		window.open(downloadUrl, '_blank')
	}

	const handleViewReport = () => {
		const viewUrl = `${API_BASE_URL}/v1/api/traces/${trace.trace_id}/html-report`
		window.open(viewUrl, '_blank')
	}

	const handleDownloadTrace = async () => {
		const downloadUrl = `${API_BASE_URL}/v1/api/traces/${trace.trace_id}/download`
		window.open(downloadUrl, '_blank')
	}

	return (
		<Layout>
			<p className="text-sm text-gray-600">Trace {trace.trace_id}</p>
			<h1 className="text-2xl font-bold">{trace.trace_name}</h1>
			<p>
				<b>Device</b> {trace.device_name} ({trace.host_name})
			</p>
			{trace.configuration_id && (
				<p>
					<b>Configuration</b> {trace.configuration_name} (
					{trace.configuration_type
						? toTitleCase(trace.configuration_type)
						: "Perfetto"}
					)
				</p>
			)}
			<div className="h-4"></div>
			
			{isSimpleperf && hasHtmlReport && (
				<>
					<div className="p-4 mb-4 border rounded-lg border-primary-200 bg-primary-50">
						<h2 className="mb-2 text-lg font-semibold">
							Simpleperf HTML Report
						</h2>
						<p className="mb-3 text-sm text-default-600">
							View the interactive profiling report generated by
							Simpleperf
						</p>
						<div className="flex gap-2">
							<Button
								color="primary"
								onPress={handleViewReport}
								size="sm"
							>
								Open in New Tab
							</Button>
							<Button
								color="primary"
								variant="bordered"
								onPress={handleDownloadReport}
								size="sm"
							>
								Download
							</Button>
						</div>
					</div>
					<div className="h-4"></div>
					<div className="border rounded-lg border-default-200">
						<iframe
							src={`${API_BASE_URL}/v1/api/traces/${trace.trace_id}/html-report`}
							className="w-full h-[600px] rounded-lg"
							title="Simpleperf HTML Report"
						/>
					</div>
				</>
			)}
			
			{isSimpleperf && !hasHtmlReport && (
				<div className="p-4 mb-4 border rounded-lg border-warning-200 bg-warning-50">
					<p className="text-sm text-warning-800">
						HTML report is being generated or is not available for
						this trace.
					</p>
				</div>
			)}
			
			{isPerfetto && (
				<>
					<InlineQueries
						showTitle
						configId={trace.configuration_id}
						onRun={(query) => setChosenQuery(query)}
					/>
					<div className="h-4"></div>
					{chosenQuery && (
						<QueryResult
							query={chosenQuery}
							traceId={trace.trace_id}
						/>
					)}
				</>
			)}
			<div className="h-4"></div>
			<div className="flex gap-2">
				<Button
					variant="bordered"
					color="primary"
					onPress={handleDownloadTrace}
				>
					Download Trace
				</Button>
				<Button
					variant="bordered"
					color="danger"
					onPress={handleDelete}
				>
					Delete Trace
				</Button>
			</div>
		</Layout>
	)
}
